"""empty message

Revision ID: 0674481f8f03
Revises: b51c7143d134
Create Date: 2023-04-26 14:25:09.754541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0674481f8f03'
down_revision = 'b51c7143d134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USERS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.Column('ip_no', sa.Integer(), nullable=True),
    sa.Column('mac_no', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('USERS')
    # ### end Alembic commands ###
