"""empty message

Revision ID: 53bbc83c6bb5
Revises: 021f34aa23ae
Create Date: 2023-05-02 23:27:56.625918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53bbc83c6bb5'
down_revision = '021f34aa23ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TEST',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TEST')
    # ### end Alembic commands ###
