"""empty message

Revision ID: 9f0dc058f27b
Revises: 53bbc83c6bb5
Create Date: 2023-05-06 06:22:16.566965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f0dc058f27b'
down_revision = '53bbc83c6bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('img', sa.String(), nullable=True))
    op.drop_column('user', 'image')
    op.drop_column('user', 'mac_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mac_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('image', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('user', 'img')
    # ### end Alembic commands ###
