"""Initial migration.

Revision ID: b51c7143d134
Revises: 38b3f5a417f6
Create Date: 2023-04-26 14:00:19.193995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51c7143d134'
down_revision = '38b3f5a417f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RESPONSE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('risk', sa.String(length=500), nullable=True),
    sa.Column('explain', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RESPONSE')
    # ### end Alembic commands ###
